export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const HIDE_SUCCESS_MESSAGE = "HIDE_SUCCESS_MESSAGE"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const HIDE_ERROR = "HIDE_ERROR"

// ==> BasicData
export const BASICDATA_REQUEST = "BASICDATA_REQUEST"
export const BASICDATA_SUCCESS = "BASICDATA_SUCCESS"
export const BASICDATA_FAILED = "BASICDATA_FAILED"

// ==> registation 
export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const REGI_REQUEST = "REGI_REQUEST"
export const REGI_SUCCESS = "REGI_SUCCESS"
export const REGI_HIDE_SUCCESS_MESSAGE = "REGI_HIDE_SUCCESS_MESSAGE"
export const REGI_FAILED = "REGI_FAILED"
export const REGI_HIDE_ERROR = "REGI_HIDE_ERROR"
